vim.keymap.set('n', '<C-m>', ':MarkdownPreviewToggle<CR>')
vim.cmd("let g:mkdp_auto_start = 0")
--vim.cmd("let g:mkdp_auto_close = 1")
--vim.cmd("let g:mkdp_refresh_slow = 0")
--vim.cmd("let g:mkdp_command_for_global = 0")
--vim.cmd("let g:mkdp_open_to_the_world = 0")
--vim.cmd("let g:mkdp_open_ip = ''")
--vim.cmd("let g:mkdp_browser = ''")
--vim.cmd("let g:mkdp_echo_preview_url = 0")
--vim.cmd("let g:mkdp_browserfunc = ''")
--local mkdp_preview_options = {
--    mkit = {},
--    katex = {},
--    uml = {},
--    maid = {},
--    disable_sync_scroll = 0,
--    sync_scroll_type = 'middle',
--    hide_yaml_meta = 1,
--    sequence_diagrams = {},
--    flowchart_diagrams = {},
--    content_editable = false,
--    disable_filename = 0,
--    toc = {}
--}
--_G["mkdp_preview_options"] = mkdp_preview_options
--vim.cmd("let g:mkdp_markdown_css = ''")
--vim.cmd("let g:mkdp_highlight_css = ''")
--vim.cmd("let g:mkdp_port = '8888'")
vim.cmd("let g:mkdp_page_title = '${name}'")
--vim.cmd("let g:mkdp_filetypes = ['markdown']")
vim.cmd("let g:mkdp_theme = 'dark'")
--vim.cmd("let g:mkdp_combine_preview = 1")
--vim.cmd("let g:mkdp_combine_preview_auto_refresh = 1")
